on:
  push:
    branches:
      - main

jobs:
  build:
    name: compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update system
        run: sudo apt update

      - name: Install SDL2
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Install Vulkan
        run: sudo apt install -y libvulkan-dev

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Make build-tracy.sh executable
        run: chmod +x ./build-tracy.sh

      - name: Run build script
        run: ./build.sh

      - name: Run build-tracy script
        run: ./build-tracy.sh

      - name: Make pack.sh executable
        run: chmod +x ./pack.sh

      - name: Pack the project
        run: ./pack.sh

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            *.so
            *.sh
